In [27]:
import pandas as pd
df = pd.read_excel(r'/home/trungdt2/Documents/GIS_VTB_Project2025/crawl_all_khoang_cach/data/full_trong_tinh_sau_sat_nhap_20250520.xlsx')

In [28]:
df.shape

(79678, 11)

In [29]:
df.head()

,Mã phòng ban 1,Tên phòng ban 1,KINH ĐỘ 1,VĨ ĐỘ 1,Mã phòng ban 2,Tên phòng ban 2,KINH ĐỘ 2,VĨ ĐỘ 2,Khoảng cách đường bộ (km),Khoảng cách chim bay (km),Tỉnh thành (sau sáp nhập)
0,36039000,PGD Bồ Xuyên,106.336744,20.449196,36041000,PGD Hoàng Công Chất,106.331829,20.438444,1.6,1.300629,Hưng Yên
1,36039000,PGD Bồ Xuyên,106.336744,20.449196,36042000,PGD Chợ Đậu,106.343223,20.433061,2.0,1.916853,Hưng Yên
2,36039000,PGD Bồ Xuyên,106.336744,20.449196,36044000,PGD Vũ Thư,106.288684,20.435725,5.8,5.226741,Hưng Yên
3,36040000,PGD Quỳnh Phụ,106.327291,20.660420,36041000,PGD Hoàng Công Chất,106.331829,20.438444,28.8,24.687114,Hưng Yên
4,36040000,PGD Quỳnh Phụ,106.327291,20.660420,36044000,PGD Vũ Thư,106.288684,20.435725,31.8,25.306250,Hưng Yên

In [30]:
df = df.dropna(subset=["Khoảng cách đường bộ (km)"])

In [31]:
df.shape

(79359, 11)

In [ ]:
import pandas as pd

# Bước 1: Tạo 2 bảng phụ để mapping từng điểm với khoảng cách
df_a = df[['Mã phòng ban 1', 'Khoảng cách đường bộ (km)']].rename(columns={
    'Mã phòng ban 1': 'Mã phòng ban'
})
df_all = pd.concat([df_a, df_b], axis=0)

# Bước 2: Lấy khoảng cách nhỏ nhất tương ứng với mỗi phòng ban
min_kc = df_all.groupby('Mã phòng ban')['Khoảng cách đường bộ (km)'].min().reset_index()
min_kc = min_kc.rename(columns={'Khoảng cách đường bộ (km)': 'MinDistance'})

# Bước 3: Gắn vào bảng gốc và lọc
# Với phòng ban 1
df_1 = df.merge(min_kc, left_on='Mã phòng ban 1', right_on='Mã phòng ban')
mask_1 = df_1['Khoảng cách đường bộ (km)'] == df_1['MinDistance']

# Với phòng ban 2
df_2 = df.merge(min_kc, left_on='Mã phòng ban 2', right_on='Mã phòng ban')
mask_2 = df_2['Khoảng cách đường bộ (km)'] == df_2['MinDistance']

# Kết hợp các dòng thỏa mãn điều kiện từ cả A và B
df_filtered = pd.concat([df_1[mask_1], df_2[mask_2]])

# Bỏ cột phụ 'MinDistance', 'Mã phòng ban' (vì từ merge)
df_filtered = df_filtered[df.columns]

In [39]:
df_filtered.head()

,Mã phòng ban 1,Tên phòng ban 1,KINH ĐỘ 1,VĨ ĐỘ 1,Mã phòng ban 2,Tên phòng ban 2,KINH ĐỘ 2,VĨ ĐỘ 2,Khoảng cách đường bộ (km),Khoảng cách chim bay (km),Tỉnh thành (sau sáp nhập)
21,38034000,PGD Nghĩa Hưng,106.184876,20.214783,38037000,PGD Nam Trực,106.176464,20.330085,13.50,12.850999,Ninh Bình
25,38035000,PGD Trực Ninh,106.266852,20.319890,38037000,PGD Nam Trực,106.176464,20.330085,12.10,9.492778,Ninh Bình
33,38200000,CN Bắc Nam Định,106.177391,20.423851,38231000,PGD Nguyễn Du,106.177585,20.428285,0.65,0.493431,Ninh Bình
36,38230000,PGD Điện Biên,106.163381,20.430319,38235000,PGD Hòa Xá,106.159552,20.421238,1.30,1.085757,Ninh Bình
42,38232000,PGD Ý Yên,106.029759,20.299991,38236000,PGD Vụ Bản,106.071838,20.330776,5.60,5.565149,Ninh Bình

In [41]:
df_filtered.shape

(2930, 11)

In [43]:
df_filtered.to_excel(r'/home/trungdt2/Documents/GIS_VTB_Project2025/crawl_all_khoang_cach/data/top1_duong_bo_trong_tinh.xlsx')

In [45]:
df_filtered.drop_duplicates(inplace = True)

In [47]:
df_filtered.shape

(1620, 11)

,Mã phòng ban 1,Tên phòng ban 1,KINH ĐỘ 1,VĨ ĐỘ 1,Mã phòng ban 2,Tên phòng ban 2,KINH ĐỘ 2,VĨ ĐỘ 2,Khoảng cách đường bộ (km),Khoảng cách chim bay (km),Tỉnh thành (sau sáp nhập)
21,38034000,PGD Nghĩa Hưng,106.184876,20.214783,38037000,PGD Nam Trực,106.176464,20.330085,13.50,12.850999,Ninh Bình
25,38035000,PGD Trực Ninh,106.266852,20.319890,38037000,PGD Nam Trực,106.176464,20.330085,12.10,9.492778,Ninh Bình
33,38200000,CN Bắc Nam Định,106.177391,20.423851,38231000,PGD Nguyễn Du,106.177585,20.428285,0.65,0.493431,Ninh Bình
36,38230000,PGD Điện Biên,106.163381,20.430319,38235000,PGD Hòa Xá,106.159552,20.421238,1.30,1.085757,Ninh Bình
42,38232000,PGD Ý Yên,106.029759,20.299991,38236000,PGD Vụ Bản,106.071838,20.330776,5.60,5.565149,Ninh Bình

In [53]:
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1620 entries, 21 to 75187
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Mã phòng ban 1             1620 non-null   int64
 1   Tên phòng ban 1            1620 non-null   object
 2   KINH ĐỘ 1                  1620 non-null   float64
 3   VĨ ĐỘ 1                    1620 non-null   float64
 4   Mã phòng ban 2             1620 non-null   int64
 5   Tên phòng ban 2            1620 non-null   object
 6   KINH ĐỘ 2                  1620 non-null   float64
 7   VĨ ĐỘ 2                    1620 non-null   float64
 8   Khoảng cách đường bộ (km)  1620 non-null   float64
 9   Khoảng cách chim bay (km)  1620 non-null   float64
 10  Tỉnh thành (sau sáp nhập)  1620 non-null   object
dtypes: float64(6), int64(2), object(3)
memory usage: 151.9+ KB

In [55]:
# Lọc ra các dòng có "Khoảng cách đường bộ (km)" nhỏ nhất theo "Mã phòng ban 1"
df_min_distance = df_filtered[
    df_filtered["Khoảng cách đường bộ (km)"] == 
    df_filtered.groupby("Mã phòng ban 1")["Khoảng cách đường bộ (km)"].transform('min')
]

In [57]:
df_min_distance.head()

,Mã phòng ban 1,Tên phòng ban 1,KINH ĐỘ 1,VĨ ĐỘ 1,Mã phòng ban 2,Tên phòng ban 2,KINH ĐỘ 2,VĨ ĐỘ 2,Khoảng cách đường bộ (km),Khoảng cách chim bay (km),Tỉnh thành (sau sáp nhập)
21,38034000,PGD Nghĩa Hưng,106.184876,20.214783,38037000,PGD Nam Trực,106.176464,20.330085,13.50,12.850999,Ninh Bình
25,38035000,PGD Trực Ninh,106.266852,20.319890,38037000,PGD Nam Trực,106.176464,20.330085,12.10,9.492778,Ninh Bình
33,38200000,CN Bắc Nam Định,106.177391,20.423851,38231000,PGD Nguyễn Du,106.177585,20.428285,0.65,0.493431,Ninh Bình
36,38230000,PGD Điện Biên,106.163381,20.430319,38235000,PGD Hòa Xá,106.159552,20.421238,1.30,1.085757,Ninh Bình
42,38232000,PGD Ý Yên,106.029759,20.299991,38236000,PGD Vụ Bản,106.071838,20.330776,5.60,5.565149,Ninh Bình

In [59]:
df_min_distance.to_excel(r'/home/trungdt2/Documents/GIS_VTB_Project2025/crawl_all_khoang_cach/data/top1_duong_bo_trong_tinh.xlsx')