In [2]:
import pandas as pd

In [3]:
df = pd.read_excel(r'/home/trungdt2/Documents/GIS_VTB_Project2025/crawl_all_khoang_cach/etl_20250604/dia_chi_toa_do_pgd_20250512.xlsx',header = 1)

In [4]:
df.head()

,Mã Đơn vị,Tên Đơn vị,Mã phòng ban,Tên phòng ban,Loại,KINH ĐỘ,VĨ ĐỘ,Tỉnh thành (hiện tại),Tỉnh thành (sau sáp nhập)
0,106,CN TP. Hà Nội,10600000,CN TP. Hà Nội,CN,105.856380,21.029475,TP. Hà Nội,TP. Hà Nội
1,106,CN TP. Hà Nội,10630000,PGD 94B Trần Hưng Đạo,PGD,105.843494,21.023420,TP. Hà Nội,TP. Hà Nội
2,106,CN TP. Hà Nội,10632000,PGD Ngô Thì Nhậm,PGD,105.852920,21.016268,TP. Hà Nội,TP. Hà Nội
3,106,CN TP. Hà Nội,10633000,PGD Lê Thạch,PGD,105.854322,21.027074,TP. Hà Nội,TP. Hà Nội
4,106,CN TP. Hà Nội,10634000,PGD Đinh Tiên Hoàng,PGD,105.852578,21.031731,TP. Hà Nội,TP. Hà Nội

In [5]:
kc = pd.read_excel(r'/home/trungdt2/Documents/GIS_VTB_Project2025/crawl_all_khoang_cach/etl_20250604/full_trong_tinh_sau_sat_nhap_20250520.xlsx')

In [6]:
kc.head()

,Mã phòng ban 1,Tên phòng ban 1,KINH ĐỘ 1,VĨ ĐỘ 1,Mã phòng ban 2,Tên phòng ban 2,KINH ĐỘ 2,VĨ ĐỘ 2,Khoảng cách đường bộ (km),Khoảng cách chim bay (km),Tỉnh thành (sau sáp nhập)
0,36039000,PGD Bồ Xuyên,106.336744,20.449196,36041000,PGD Hoàng Công Chất,106.331829,20.438444,1.6,1.300629,Hưng Yên
1,36039000,PGD Bồ Xuyên,106.336744,20.449196,36042000,PGD Chợ Đậu,106.343223,20.433061,2.0,1.916853,Hưng Yên
2,36039000,PGD Bồ Xuyên,106.336744,20.449196,36044000,PGD Vũ Thư,106.288684,20.435725,5.8,5.226741,Hưng Yên
3,36040000,PGD Quỳnh Phụ,106.327291,20.660420,36041000,PGD Hoàng Công Chất,106.331829,20.438444,28.8,24.687114,Hưng Yên
4,36040000,PGD Quỳnh Phụ,106.327291,20.660420,36044000,PGD Vũ Thư,106.288684,20.435725,31.8,25.306250,Hưng Yên

In [8]:
df_ma_tinh_cu = df[['Mã phòng ban','Tỉnh thành (hiện tại)']]

In [9]:
df_ma_tinh_cu.head()

   Mã phòng ban Tỉnh thành (hiện tại)
0      10600000            TP. Hà Nội
1      10630000            TP. Hà Nội
2      10632000            TP. Hà Nội
3      10633000            TP. Hà Nội
4      10634000            TP. Hà Nội

In [10]:
kc = pd.merge(kc,df_ma_tinh_cu,left_on='Mã phòng ban 1',right_on='Mã phòng ban',how='left')
del kc['Mã phòng ban']

In [11]:
kc.head()

,Mã phòng ban 1,Tên phòng ban 1,KINH ĐỘ 1,VĨ ĐỘ 1,Mã phòng ban 2,Tên phòng ban 2,KINH ĐỘ 2,VĨ ĐỘ 2,Khoảng cách đường bộ (km),Khoảng cách chim bay (km),Tỉnh thành (sau sáp nhập),Tỉnh thành (hiện tại)
0,36039000,PGD Bồ Xuyên,106.336744,20.449196,36041000,PGD Hoàng Công Chất,106.331829,20.438444,1.6,1.300629,Hưng Yên,Thái Bình
1,36039000,PGD Bồ Xuyên,106.336744,20.449196,36042000,PGD Chợ Đậu,106.343223,20.433061,2.0,1.916853,Hưng Yên,Thái Bình
2,36039000,PGD Bồ Xuyên,106.336744,20.449196,36044000,PGD Vũ Thư,106.288684,20.435725,5.8,5.226741,Hưng Yên,Thái Bình
3,36040000,PGD Quỳnh Phụ,106.327291,20.660420,36041000,PGD Hoàng Công Chất,106.331829,20.438444,28.8,24.687114,Hưng Yên,Thái Bình
4,36040000,PGD Quỳnh Phụ,106.327291,20.660420,36044000,PGD Vũ Thư,106.288684,20.435725,31.8,25.306250,Hưng Yên,Thái Bình

In [12]:
kc = pd.merge(kc,df_ma_tinh_cu,left_on='Mã phòng ban 2',right_on='Mã phòng ban',how='left')
del kc['Mã phòng ban']

In [17]:
kc[kc['Tỉnh thành (hiện tại)_x']=='Thái Bình']

,Mã phòng ban 1,Tên phòng ban 1,KINH ĐỘ 1,VĨ ĐỘ 1,Mã phòng ban 2,Tên phòng ban 2,KINH ĐỘ 2,VĨ ĐỘ 2,Khoảng cách đường bộ (km),Khoảng cách chim bay (km),Tỉnh thành (sau sáp nhập),Tỉnh thành (hiện tại)_x,Tỉnh thành (hiện tại)_y
0,36039000,PGD Bồ Xuyên,106.336744,20.449196,36041000,PGD Hoàng Công Chất,106.331829,20.438444,1.6,1.300629,Hưng Yên,Thái Bình,Thái Bình
1,36039000,PGD Bồ Xuyên,106.336744,20.449196,36042000,PGD Chợ Đậu,106.343223,20.433061,2.0,1.916853,Hưng Yên,Thái Bình,Thái Bình
2,36039000,PGD Bồ Xuyên,106.336744,20.449196,36044000,PGD Vũ Thư,106.288684,20.435725,5.8,5.226741,Hưng Yên,Thái Bình,Thái Bình
3,36040000,PGD Quỳnh Phụ,106.327291,20.660420,36041000,PGD Hoàng Công Chất,106.331829,20.438444,28.8,24.687114,Hưng Yên,Thái Bình,Thái Bình
4,36040000,PGD Quỳnh Phụ,106.327291,20.660420,36044000,PGD Vũ Thư,106.288684,20.435725,31.8,25.306250,Hưng Yên,Thái Bình,Thái Bình
...,...,...,...,...,...,...,...,...,...,...,...,...,...
51752,36040000,PGD Quỳnh Phụ,106.327291,20.660420,36039000,PGD Bồ Xuyên,106.336744,20.449196,27.6,23.507672,Hưng Yên,Thái Bình,Thái Bình
52042,36000000,CN Thái Bình,106.340722,20.446466,34200000,CN Hưng Yên,106.057986,20.654164,45.2,37.416352,Hưng Yên,Thái Bình,Hưng Yên
52043,36030000,PGD Minh Khai,106.340405,20.451573,34200000,CN Hưng Yên,106.057986,20.654164,44.9,37.041887,Hưng Yên,Thái Bình,Hưng Yên
52044,36031000,PGD Trần Hưng Đạo,106.333864,20.441776,34200000,CN Hưng Yên,106.057986,20.654164,45.3,37.186518,Hưng Yên,Thái Bình,Hưng Yên
52045,36032000,PGD Lê Hồng Phong,106.346773,20.450135,34200000,CN Hưng Yên,106.057986,20.654164,45.9,37.666586,Hưng Yên,Thái Bình,Hưng Yên

In [18]:
# Lọc các dòng có giá trị của 'Tỉnh thành (hiện tại)_x' bằng 'Tỉnh thành (hiện tại)_y'
filtered_kc = kc[kc['Tỉnh thành (hiện tại)_x'] == kc['Tỉnh thành (hiện tại)_y']]

In [19]:
filtered_kc.head()

,Mã phòng ban 1,Tên phòng ban 1,KINH ĐỘ 1,VĨ ĐỘ 1,Mã phòng ban 2,Tên phòng ban 2,KINH ĐỘ 2,VĨ ĐỘ 2,Khoảng cách đường bộ (km),Khoảng cách chim bay (km),Tỉnh thành (sau sáp nhập),Tỉnh thành (hiện tại)_x,Tỉnh thành (hiện tại)_y
0,36039000,PGD Bồ Xuyên,106.336744,20.449196,36041000,PGD Hoàng Công Chất,106.331829,20.438444,1.6,1.300629,Hưng Yên,Thái Bình,Thái Bình
1,36039000,PGD Bồ Xuyên,106.336744,20.449196,36042000,PGD Chợ Đậu,106.343223,20.433061,2.0,1.916853,Hưng Yên,Thái Bình,Thái Bình
2,36039000,PGD Bồ Xuyên,106.336744,20.449196,36044000,PGD Vũ Thư,106.288684,20.435725,5.8,5.226741,Hưng Yên,Thái Bình,Thái Bình
3,36040000,PGD Quỳnh Phụ,106.327291,20.660420,36041000,PGD Hoàng Công Chất,106.331829,20.438444,28.8,24.687114,Hưng Yên,Thái Bình,Thái Bình
4,36040000,PGD Quỳnh Phụ,106.327291,20.660420,36044000,PGD Vũ Thư,106.288684,20.435725,31.8,25.306250,Hưng Yên,Thái Bình,Thái Bình

In [20]:
# Lọc ra các dòng có "Khoảng cách đường bộ (km)" nhỏ nhất theo "Mã phòng ban 1"
df_min_distance = filtered_kc[
    filtered_kc["Khoảng cách đường bộ (km)"] == 
    filtered_kc.groupby("Mã phòng ban 1")["Khoảng cách đường bộ (km)"].transform('min')
]

In [23]:
df_min_distance.head()

,Mã phòng ban 1,Tên phòng ban 1,KINH ĐỘ 1,VĨ ĐỘ 1,Mã phòng ban 2,Tên phòng ban 2,KINH ĐỘ 2,VĨ ĐỘ 2,Khoảng cách đường bộ (km),Khoảng cách chim bay (km),Tỉnh thành (hiện tại)_y
21,38034000,PGD Nghĩa Hưng,106.184876,20.214783,38037000,PGD Nam Trực,106.176464,20.330085,13.50,12.850999,Nam Định
25,38035000,PGD Trực Ninh,106.266852,20.319890,38037000,PGD Nam Trực,106.176464,20.330085,12.10,9.492778,Nam Định
33,38200000,CN Bắc Nam Định,106.177391,20.423851,38231000,PGD Nguyễn Du,106.177585,20.428285,0.65,0.493431,Nam Định
36,38230000,PGD Điện Biên,106.163381,20.430319,38235000,PGD Hòa Xá,106.159552,20.421238,1.30,1.085757,Nam Định
42,38232000,PGD Ý Yên,106.029759,20.299991,38236000,PGD Vụ Bản,106.071838,20.330776,5.60,5.565149,Nam Định

In [22]:
del df_min_distance['Tỉnh thành (sau sáp nhập)']
del df_min_distance['Tỉnh thành (hiện tại)_x']

In [24]:
df_min_distance.to_excel(r'/home/trungdt2/Documents/GIS_VTB_Project2025/crawl_all_khoang_cach/etl_20250604/tinh_cu_20250604.xlsx')