In [1]:
pwd

'/home/trungdt2/Documents/GIS_VTB_Project2025/crawl_all_khoang_cach'

In [2]:
import pandas as pd
import os

In [3]:
os.listdir('./data_20260313/')

['danh_sach_tinh_cu_moi.xlsx',
 'full_trong_tinh_sau_sat_nhap_20260312.xlsx',
 '20250520_khoang_cach_cac_diem_gd_trong_tinh_sau_sat_nhap.xlsx',
 'template.xlsx',
 '20260313_ML_02_TUxlsx.xlsx',
 '.~lock.template.xlsx#',
 'sample_ml_thay_doi_drop_2025_sang_2026_head.csv',
 'output_2026',
 'template_sheet1.xlsx',
 'template_sheet2.xlsx']

In [4]:
ml_2026 = pd.read_excel(r'./data_20260313/20260313_ML_02_TUxlsx.xlsx',skiprows=1)

In [5]:
ml_2026.columns

Index(['Khối', 'SetID', 'Mã Đơn vị', 'Tên Đơn vị', 'Mã phòng ban',
       'Ngày hiệu lực', 'Trạng thái', 'Tên phòng ban', 'Mã công ty',
       'Mã Địa điểm', 'Tên  địa điểm', 'Địa chỉ', 'Quận huyện', 'Tỉnh thành',
       'Số điện thoại', 'Số mở rộng', 'Fax', 'lý do thay đổi',
       'Ngày hoạt động', 'Khu vực', 'Loại ĐV', 'Loại đơn vị', 'Khối.1',
       'Loại phòng', 'Loại phòng.1', 'Mã loại phòng', 'Hạng đô thị',
       'Mã quản lý phòng', 'Tên quản lý phòng', 'Khoảng cách tới TS CN',
       'Số QĐ thành lập', 'Ngày QĐ', 'Văn bản chấp thuận NHNN', 'Ngày QĐ NHNN',
       'Số quyết định mới nhất', 'Ngày quyết định', 'Mặt tiền', 'Diện tích',
       'Diện tích SGD', 'Thời gian cập nhật cuối cùng', 'Người cập nhật',
       'Tên group email', 'KINH ĐỘ', 'VĨ ĐỘ', 'Sở hữu', 'Ngày thuê',
       'Ngày kết thúc', 'GIỜ MỞ CỬA SÁNG', 'GIỜ ĐÓNG CỬA SÁ', 'MỞ CỬA CHIỀU',
       'ĐÓNG CỬA CHIỀU', 'Xã phường mới', 'Mô tả'],
      dtype='object')

In [6]:
import unicodedata
import re

def normalize_column_name(col):
    # chuyển Đ đ trước khi remove accent
    col = col.replace("Đ", "D").replace("đ", "d")
    
    # bỏ dấu tiếng Việt
    col = unicodedata.normalize("NFKD", col)
    col = "".join(c for c in col if not unicodedata.combining(c))
    
    # lower
    col = col.lower()
    
    # bỏ khoảng trắng đầu cuối
    col = col.strip()
    
    # thay khoảng trắng bằng _
    col = re.sub(r"\s+", "_", col)
    
    # thay . bằng _
    col = col.replace(".", "_")
    
    # bỏ ký tự đặc biệt
    col = re.sub(r"[^a-z0-9_]", "", col)
    
    # bỏ _ trùng nhau
    col = re.sub(r"_+", "_", col)
    
    return col

In [7]:
# chuẩn hóa tên cột của df bỏ dấu lower
ml_2026.columns = [normalize_column_name(col) for col in ml_2026.columns]

In [8]:
# lấy danh sách chi nhanh
ml_2026.khoi.unique()
ml_2026 = ml_2026[ml_2026.khoi == 'Chi nhánh']
cols = ['ma_phong_ban', 'ten_phong_ban', 'kinh_do', 'vi_do','tinh_thanh']
ml_2026 = ml_2026[cols]

In [9]:
ml_2026.columns

Index(['ma_phong_ban', 'ten_phong_ban', 'kinh_do', 'vi_do', 'tinh_thanh'], dtype='object')

In [10]:
ml_2026.tinh_thanh.unique()

array(['TP. Hà Nội', 'TP. Hải Phòng', 'Lào Cai', 'Thái Nguyên',
       'Tuyên Quang', 'Lai Châu', 'Điện Biên', 'Cao Bằng', 'Sơn La',
       'Lạng Sơn', 'Phú Thọ', 'Bắc Ninh', 'Quảng Ninh', 'Hưng Yên',
       'Ninh Bình', 'Thanh Hoá', 'Hà Tĩnh', 'Nghệ An', 'Quảng Trị', 'Huế',
       'TP. Đà Nẵng', 'Gia Lai', 'Đắk Lắk', 'Đồng Nai', 'Lâm Đồng',
       'Quảng Ngãi', 'Khánh Hoà', 'TP. Hồ Chí Minh', 'Tây Ninh',
       'Đồng Tháp', 'An Giang', 'Vĩnh Long', 'TP. Cần Thơ', 'Cà Mau'],
      dtype=object)

In [11]:
ml_2026.head()

   ma_phong_ban          ten_phong_ban     kinh_do      vi_do  tinh_thanh
76    010600000    CN Thành phố Hà Nội  105.856380  21.029475  TP. Hà Nội
77    010630000  PGD 94B Trần Hưng Đạo  105.843494  21.023420  TP. Hà Nội
78    010632000       PGD Ngô Thì Nhậm  105.852920  21.016268  TP. Hà Nội
79    010633000           PGD Lê Thạch  105.854322  21.027074  TP. Hà Nội
80    010634000    PGD Đinh Tiên Hoàng  105.852578  21.031731  TP. Hà Nội

In [12]:
import pandas as pd
from itertools import permutations
from math import radians, sin, cos, sqrt, atan2

# Hàm tính khoảng cách chim bay (Haversine)
def haversine(lon1, lat1, lon2, lat2):
    R = 6371  # bán kính trái đất (km)

    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2) ** 2 + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    return R * c


result = []

for tinh_thanh, group in ml_2026.groupby("tinh_thanh"):
    
    records = group[["ma_phong_ban", "ten_phong_ban", "kinh_do", "vi_do"]].to_dict("records")

    # permutations để lấy cả AB và BA
    for r1, r2 in permutations(records, 2):

        khoang_cach = haversine(
            r1["kinh_do"], r1["vi_do"],
            r2["kinh_do"], r2["vi_do"]
        )

        result.append({
            "ma_phong_ban_1": r1["ma_phong_ban"],
            "ten_phong_ban_1": r1["ten_phong_ban"],
            "kinh_do_1": r1["kinh_do"],
            "vi_do_1": r1["vi_do"],
            "ma_phong_ban_2": r2["ma_phong_ban"],
            "ten_phong_ban_2": r2["ten_phong_ban"],
            "kinh_do_2": r2["kinh_do"],
            "vi_do_2": r2["vi_do"],
            "khoang_cach_chim_bay": khoang_cach,
            "tinh_thanh": tinh_thanh
        })

ml_2026_to_hop = pd.DataFrame(result)
ml_2026_to_hop['ma_phong_ban_1'] = ml_2026_to_hop['ma_phong_ban_1'].astype('int64')
ml_2026_to_hop['ma_phong_ban_2'] = ml_2026_to_hop['ma_phong_ban_2'].astype('int64')

In [13]:
ml_2026_to_hop.head()

,ma_phong_ban_1,ten_phong_ban_1,kinh_do_1,vi_do_1,ma_phong_ban_2,ten_phong_ban_2,kinh_do_2,vi_do_2,khoang_cach_chim_bay,tinh_thanh
0,74000000,CN An Giang,105.443461,10.378568,74030000,PGD Long Xuyên,105.440750,10.383611,0.634311,An Giang
1,74000000,CN An Giang,105.443461,10.378568,74031000,PGD Thoại Sơn,105.269688,10.268097,22.633351,An Giang
2,74000000,CN An Giang,105.443461,10.378568,74032000,PGD Chợ Mới,105.402299,10.549315,19.512402,An Giang
3,74000000,CN An Giang,105.443461,10.378568,74033000,PGD Châu Thành,105.377066,10.444832,10.344841,An Giang
4,74000000,CN An Giang,105.443461,10.378568,74034000,PGD Châu Phú,105.241432,10.569769,30.659272,An Giang

In [14]:
ml_2026_to_hop.shape

(61500, 10)

In [15]:
ml_2025 = pd.read_excel(r'./data_20260313/20250520_khoang_cach_cac_diem_gd_trong_tinh_sau_sat_nhap.xlsx')
# chuẩn hóa tên cột của df bỏ dấu lower
ml_2025.columns = [normalize_column_name(col) for col in ml_2025.columns]

In [16]:
ml_2025.head(2)

,ma_phong_ban_1,ten_phong_ban_1,kinh_do_1,vi_do_1,ma_phong_ban_2,ten_phong_ban_2,kinh_do_2,vi_do_2,khoang_cach_duong_bo_km,khoang_cach_chim_bay_km,tinh_thanh_sau_sap_nhap
0,36039000,PGD Bồ Xuyên,106.336744,20.449196,36041000,PGD Hoàng Công Chất,106.331829,20.438444,1.6,1.300629,Hưng Yên
1,36039000,PGD Bồ Xuyên,106.336744,20.449196,36042000,PGD Chợ Đậu,106.343223,20.433061,2.0,1.916853,Hưng Yên

In [17]:
ml_2026_to_hop.head(2)

,ma_phong_ban_1,ten_phong_ban_1,kinh_do_1,vi_do_1,ma_phong_ban_2,ten_phong_ban_2,kinh_do_2,vi_do_2,khoang_cach_chim_bay,tinh_thanh
0,74000000,CN An Giang,105.443461,10.378568,74030000,PGD Long Xuyên,105.440750,10.383611,0.634311,An Giang
1,74000000,CN An Giang,105.443461,10.378568,74031000,PGD Thoại Sơn,105.269688,10.268097,22.633351,An Giang

In [18]:
ml_2026_to_hop.columns

Index(['ma_phong_ban_1', 'ten_phong_ban_1', 'kinh_do_1', 'vi_do_1',
       'ma_phong_ban_2', 'ten_phong_ban_2', 'kinh_do_2', 'vi_do_2',
       'khoang_cach_chim_bay', 'tinh_thanh'],
      dtype='object')

In [19]:
cols = [
'ma_phong_ban_1','ten_phong_ban_1','kinh_do_1','vi_do_1',
'ma_phong_ban_2','ten_phong_ban_2','kinh_do_2','vi_do_2'
]

ml_khong_doi = ml_2025.merge(
    ml_2026_to_hop[cols],
    on=cols,
    how='inner'
)

In [20]:
ml_khong_doi.head()

,ma_phong_ban_1,ten_phong_ban_1,kinh_do_1,vi_do_1,ma_phong_ban_2,ten_phong_ban_2,kinh_do_2,vi_do_2,khoang_cach_duong_bo_km,khoang_cach_chim_bay_km,tinh_thanh_sau_sap_nhap
0,36039000,PGD Bồ Xuyên,106.336744,20.449196,36042000,PGD Chợ Đậu,106.343223,20.433061,2.0,1.916853,Hưng Yên
1,36039000,PGD Bồ Xuyên,106.336744,20.449196,36044000,PGD Vũ Thư,106.288684,20.435725,5.8,5.226741,Hưng Yên
2,36040000,PGD Quỳnh Phụ,106.327291,20.660420,36044000,PGD Vũ Thư,106.288684,20.435725,31.8,25.306250,Hưng Yên
3,36040000,PGD Quỳnh Phụ,106.327291,20.660420,36042000,PGD Chợ Đậu,106.343223,20.433061,29.6,25.335477,Hưng Yên
4,36042000,PGD Chợ Đậu,106.343223,20.433061,36044000,PGD Vũ Thư,106.288684,20.435725,7.3,5.690572,Hưng Yên

In [21]:
ml_khong_doi.shape

(52456, 11)

In [22]:
cols = [
'ma_phong_ban_1','ten_phong_ban_1','kinh_do_1','vi_do_1',
'ma_phong_ban_2','ten_phong_ban_2','kinh_do_2','vi_do_2'
]

ml_thay_doi = ml_2026_to_hop.merge(
    ml_2025[cols],
    on=cols,
    how='left',
    indicator=True
)

ml_thay_doi = ml_thay_doi[ml_thay_doi['_merge'] == 'left_only'] \
                .drop(columns=['_merge'])

In [23]:
ml_thay_doi.head()

,ma_phong_ban_1,ten_phong_ban_1,kinh_do_1,vi_do_1,ma_phong_ban_2,ten_phong_ban_2,kinh_do_2,vi_do_2,khoang_cach_chim_bay,tinh_thanh
0,74000000,CN An Giang,105.443461,10.378568,74030000,PGD Long Xuyên,105.440750,10.383611,0.634311,An Giang
26,74030000,PGD Long Xuyên,105.440750,10.383611,74000000,CN An Giang,105.443461,10.378568,0.634311,An Giang
27,74030000,PGD Long Xuyên,105.440750,10.383611,74031000,PGD Thoại Sơn,105.269688,10.268097,22.697256,An Giang
28,74030000,PGD Long Xuyên,105.440750,10.383611,74032000,PGD Chợ Mới,105.402299,10.549315,18.899071,An Giang
29,74030000,PGD Long Xuyên,105.440750,10.383611,74033000,PGD Châu Thành,105.377066,10.444832,9.739006,An Giang

In [24]:
output = r'./data_20260313/output_2026'

if not os.path.exists(output):
    os.mkdir(output)

# lấy phần Ml_không đổi ra  lưu vào rồi ghép sau 
# ml_khong_doi.to_excel(os.path.join(output,'ml_khong_doi_2025_sang_2026.xlsx'),index=False)

In [25]:
# ml_thay_doi.to_excel(os.path.join(output,'ml_thay_doi_2025_sang_2026.xlsx'),index=False)

In [26]:
ml_thay_doi.head()

,ma_phong_ban_1,ten_phong_ban_1,kinh_do_1,vi_do_1,ma_phong_ban_2,ten_phong_ban_2,kinh_do_2,vi_do_2,khoang_cach_chim_bay,tinh_thanh
0,74000000,CN An Giang,105.443461,10.378568,74030000,PGD Long Xuyên,105.440750,10.383611,0.634311,An Giang
26,74030000,PGD Long Xuyên,105.440750,10.383611,74000000,CN An Giang,105.443461,10.378568,0.634311,An Giang
27,74030000,PGD Long Xuyên,105.440750,10.383611,74031000,PGD Thoại Sơn,105.269688,10.268097,22.697256,An Giang
28,74030000,PGD Long Xuyên,105.440750,10.383611,74032000,PGD Chợ Mới,105.402299,10.549315,18.899071,An Giang
29,74030000,PGD Long Xuyên,105.440750,10.383611,74033000,PGD Châu Thành,105.377066,10.444832,9.739006,An Giang

In [27]:
cols = ['ma_phong_ban_1','ma_phong_ban_2']

# tạo key cặp không thứ tự
ml_thay_doi['pair_key'] = ml_thay_doi[cols].apply(lambda x: tuple(sorted(x)), axis=1)

# drop AB/BA
ml_thay_doi_drop = ml_thay_doi.drop_duplicates('pair_key').drop(columns='pair_key')

In [28]:
ml_thay_doi_drop.shape

(5525, 10)

In [29]:
ml_thay_doi_drop.to_excel(os.path.join(output,'ml_thay_doi_drop_2025_sang_2026.xlsx'),index=False)

In [30]:
ml_thay_doi_drop.head()

,ma_phong_ban_1,ten_phong_ban_1,kinh_do_1,vi_do_1,ma_phong_ban_2,ten_phong_ban_2,kinh_do_2,vi_do_2,khoang_cach_chim_bay,tinh_thanh
0,74000000,CN An Giang,105.443461,10.378568,74030000,PGD Long Xuyên,105.440750,10.383611,0.634311,An Giang
27,74030000,PGD Long Xuyên,105.440750,10.383611,74031000,PGD Thoại Sơn,105.269688,10.268097,22.697256,An Giang
28,74030000,PGD Long Xuyên,105.440750,10.383611,74032000,PGD Chợ Mới,105.402299,10.549315,18.899071,An Giang
29,74030000,PGD Long Xuyên,105.440750,10.383611,74033000,PGD Châu Thành,105.377066,10.444832,9.739006,An Giang
30,74030000,PGD Long Xuyên,105.440750,10.383611,74034000,PGD Châu Phú,105.241432,10.569769,30.057375,An Giang

# Append data mới

In [31]:
# concat data mới
new_folder_path = r'/home/trungdt2/Documents/GIS_VTB_Project2025/crawl_all_khoang_cach/part'

dfs = []

for root, dirs, files in os.walk(new_folder_path):
    for file in files:
        if file.endswith(".xlsx"):
            file_path = os.path.join(root, file)
            # print("Reading:", file_path)

            df = pd.read_excel(file_path)
            dfs.append(df)

# gộp tất cả dataframe
df_thay_doi_new = pd.concat(dfs, ignore_index=True)

In [32]:
df_thay_doi_new.head()

,ma_phong_ban_1,ten_phong_ban_1,kinh_do_1,vi_do_1,ma_phong_ban_2,ten_phong_ban_2,kinh_do_2,vi_do_2,khoang_cach_chim_bay,tinh_thanh,Khoảng cách đường bộ
0,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94030000,PGD Lý Thường Kiệt,106.657650,10.771648,2.662460,TP. Hồ Chí Minh,14 min\n3.7 km
1,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94031000,PGD Ngô Gia Tự,106.674839,10.767055,0.832554,TP. Hồ Chí Minh,7 min\n2.0 km
2,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94032000,PGD Ngô Quyền,106.664916,10.762539,2.026162,TP. Hồ Chí Minh,10 min\n2.4 km
3,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94033000,PGD Tô Hiến Thành,106.668015,10.779648,1.877803,TP. Hồ Chí Minh,14 min\n3.6 km
4,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94200000,CN 11 Thành phố Hồ Chí Minh,106.647436,10.756821,4.035046,TP. Hồ Chí Minh,18 min\n5.5 km

In [33]:
df_thay_doi_new.columns

Index(['ma_phong_ban_1', 'ten_phong_ban_1', 'kinh_do_1', 'vi_do_1',
       'ma_phong_ban_2', 'ten_phong_ban_2', 'kinh_do_2', 'vi_do_2',
       'khoang_cach_chim_bay', 'tinh_thanh', 'Khoảng cách đường bộ'],
      dtype='object')

In [34]:
ml_khong_doi.head()

,ma_phong_ban_1,ten_phong_ban_1,kinh_do_1,vi_do_1,ma_phong_ban_2,ten_phong_ban_2,kinh_do_2,vi_do_2,khoang_cach_duong_bo_km,khoang_cach_chim_bay_km,tinh_thanh_sau_sap_nhap
0,36039000,PGD Bồ Xuyên,106.336744,20.449196,36042000,PGD Chợ Đậu,106.343223,20.433061,2.0,1.916853,Hưng Yên
1,36039000,PGD Bồ Xuyên,106.336744,20.449196,36044000,PGD Vũ Thư,106.288684,20.435725,5.8,5.226741,Hưng Yên
2,36040000,PGD Quỳnh Phụ,106.327291,20.660420,36044000,PGD Vũ Thư,106.288684,20.435725,31.8,25.306250,Hưng Yên
3,36040000,PGD Quỳnh Phụ,106.327291,20.660420,36042000,PGD Chợ Đậu,106.343223,20.433061,29.6,25.335477,Hưng Yên
4,36042000,PGD Chợ Đậu,106.343223,20.433061,36044000,PGD Vũ Thư,106.288684,20.435725,7.3,5.690572,Hưng Yên

In [35]:
df_ab = df_thay_doi_new.copy()

df_ba = df_ab.copy()

# swap các cột
cols_1 = ['ma_phong_ban_1','ten_phong_ban_1','kinh_do_1','vi_do_1']
cols_2 = ['ma_phong_ban_2','ten_phong_ban_2','kinh_do_2','vi_do_2']

df_ba[cols_1], df_ba[cols_2] = df_ab[cols_2].values, df_ab[cols_1].values

# gộp lại
df_AB_BA = pd.concat([df_ab, df_ba], ignore_index=True)

In [36]:
df_AB_BA.shape

(11050, 11)

In [37]:
df_AB_BA.head()

,ma_phong_ban_1,ten_phong_ban_1,kinh_do_1,vi_do_1,ma_phong_ban_2,ten_phong_ban_2,kinh_do_2,vi_do_2,khoang_cach_chim_bay,tinh_thanh,Khoảng cách đường bộ
0,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94030000,PGD Lý Thường Kiệt,106.65765,10.771648,2.662460,TP. Hồ Chí Minh,14 min\n3.7 km
1,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94031000,PGD Ngô Gia Tự,106.674839,10.767055,0.832554,TP. Hồ Chí Minh,7 min\n2.0 km
2,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94032000,PGD Ngô Quyền,106.664916,10.762539,2.026162,TP. Hồ Chí Minh,10 min\n2.4 km
3,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94033000,PGD Tô Hiến Thành,106.668015,10.779648,1.877803,TP. Hồ Chí Minh,14 min\n3.6 km
4,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94200000,CN 11 Thành phố Hồ Chí Minh,106.647436,10.756821,4.035046,TP. Hồ Chí Minh,18 min\n5.5 km

# tach thoi gian va khoang cach

In [38]:
import pandas as pd
import re

def tach_khoang_cach_va_thoi_gian(text):
    if pd.isna(text) or "Không tìm thấy" in str(text):
        return pd.Series([None, None])
    
    text = str(text).replace('\n', ' ').strip().lower()

    # Trường hợp: "1 hr 27 min 36.6 km"
    match = re.search(r'(?:(\d+)\s*hr)?\s*(\d+)?\s*min.*?([\d.]+)\s*(km|m)', text)
    if match:
        hours = int(match.group(1)) if match.group(1) else 0
        mins = int(match.group(2)) if match.group(2) else 0
        distance = float(match.group(3))
        unit = match.group(4)
        total_mins = hours * 60 + mins
        distance_km = distance / 1000 if unit == 'm' else distance
        return pd.Series([total_mins, distance_km])

    # Trường hợp: "2 min 750 m" (không có hr)
    match = re.search(r'(\d+)\s*min.*?([\d.]+)\s*(km|m)', text)
    if match:
        mins = int(match.group(1))
        distance = float(match.group(2))
        unit = match.group(3)
        distance_km = distance / 1000 if unit == 'm' else distance
        return pd.Series([mins, distance_km])

    # Trường hợp chỉ có "1 hr 48.9 km"
    match = re.search(r'(\d+)\s*hr.*?([\d.]+)\s*(km|m)', text)
    if match:
        hours = int(match.group(1))
        distance = float(match.group(2))
        unit = match.group(3)
        distance_km = distance / 1000 if unit == 'm' else distance
        return pd.Series([hours * 60, distance_km])

    # Trường hợp chỉ có khoảng cách, ví dụ: "600 m" hoặc "31.8 km"
    match = re.search(r'([\d.]+)\s*(km|m)', text)
    if match:
        distance = float(match.group(1))
        unit = match.group(2)
        distance_km = distance / 1000 if unit == 'm' else distance
        return pd.Series([None, distance_km])

    return pd.Series([None, None])

In [39]:
df_AB_BA[['Thời gian (phút)', 'Khoảng cách (km)']] = df_AB_BA['Khoảng cách đường bộ'].apply(tach_khoang_cach_va_thoi_gian)

In [40]:
df_AB_BA.columns

Index(['ma_phong_ban_1', 'ten_phong_ban_1', 'kinh_do_1', 'vi_do_1',
       'ma_phong_ban_2', 'ten_phong_ban_2', 'kinh_do_2', 'vi_do_2',
       'khoang_cach_chim_bay', 'tinh_thanh', 'Khoảng cách đường bộ',
       'Thời gian (phút)', 'Khoảng cách (km)'],
      dtype='object')

In [41]:
ml_khong_doi.columns

Index(['ma_phong_ban_1', 'ten_phong_ban_1', 'kinh_do_1', 'vi_do_1',
       'ma_phong_ban_2', 'ten_phong_ban_2', 'kinh_do_2', 'vi_do_2',
       'khoang_cach_duong_bo_km', 'khoang_cach_chim_bay_km',
       'tinh_thanh_sau_sap_nhap'],
      dtype='object')

In [42]:
df_AB_BA.head(1)

,ma_phong_ban_1,ten_phong_ban_1,kinh_do_1,vi_do_1,ma_phong_ban_2,ten_phong_ban_2,kinh_do_2,vi_do_2,khoang_cach_chim_bay,tinh_thanh,Khoảng cách đường bộ,Thời gian (phút),Khoảng cách (km)
0,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94030000,PGD Lý Thường Kiệt,106.65765,10.771648,2.66246,TP. Hồ Chí Minh,14 min\n3.7 km,14.0,3.7

In [43]:
cols_temp = ['ma_phong_ban_1', 'ten_phong_ban_1', 'kinh_do_1', 'vi_do_1',
       'ma_phong_ban_2', 'ten_phong_ban_2', 'kinh_do_2', 'vi_do_2',
       'Khoảng cách (km)','khoang_cach_chim_bay', 'tinh_thanh']
df_thay_doi_new_etl = df_AB_BA[cols_temp]

df_thay_doi_new_etl.rename(
    columns={
        'Khoảng cách (km)':'khoang_cach_duong_bo_km',
        'tinh_thanh':'tinh_thanh_sau_sap_nhap',
        'khoang_cach_chim_bay':'khoang_cach_chim_bay_km'
    },inplace=True
)

/tmp/ipykernel_20925/2866064738.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_thay_doi_new_etl.rename(

In [44]:
df_thay_doi_new_etl.head()

,ma_phong_ban_1,ten_phong_ban_1,kinh_do_1,vi_do_1,ma_phong_ban_2,ten_phong_ban_2,kinh_do_2,vi_do_2,khoang_cach_duong_bo_km,khoang_cach_chim_bay_km,tinh_thanh_sau_sap_nhap
0,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94030000,PGD Lý Thường Kiệt,106.65765,10.771648,3.7,2.662460,TP. Hồ Chí Minh
1,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94031000,PGD Ngô Gia Tự,106.674839,10.767055,2.0,0.832554,TP. Hồ Chí Minh
2,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94032000,PGD Ngô Quyền,106.664916,10.762539,2.4,2.026162,TP. Hồ Chí Minh
3,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94033000,PGD Tô Hiến Thành,106.668015,10.779648,3.6,1.877803,TP. Hồ Chí Minh
4,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94200000,CN 11 Thành phố Hồ Chí Minh,106.647436,10.756821,5.5,4.035046,TP. Hồ Chí Minh

In [45]:
df_thay_doi_new_etl.columns

Index(['ma_phong_ban_1', 'ten_phong_ban_1', 'kinh_do_1', 'vi_do_1',
       'ma_phong_ban_2', 'ten_phong_ban_2', 'kinh_do_2', 'vi_do_2',
       'khoang_cach_duong_bo_km', 'khoang_cach_chim_bay_km',
       'tinh_thanh_sau_sap_nhap'],
      dtype='object')

In [46]:
ml_khong_doi.head()

,ma_phong_ban_1,ten_phong_ban_1,kinh_do_1,vi_do_1,ma_phong_ban_2,ten_phong_ban_2,kinh_do_2,vi_do_2,khoang_cach_duong_bo_km,khoang_cach_chim_bay_km,tinh_thanh_sau_sap_nhap
0,36039000,PGD Bồ Xuyên,106.336744,20.449196,36042000,PGD Chợ Đậu,106.343223,20.433061,2.0,1.916853,Hưng Yên
1,36039000,PGD Bồ Xuyên,106.336744,20.449196,36044000,PGD Vũ Thư,106.288684,20.435725,5.8,5.226741,Hưng Yên
2,36040000,PGD Quỳnh Phụ,106.327291,20.660420,36044000,PGD Vũ Thư,106.288684,20.435725,31.8,25.306250,Hưng Yên
3,36040000,PGD Quỳnh Phụ,106.327291,20.660420,36042000,PGD Chợ Đậu,106.343223,20.433061,29.6,25.335477,Hưng Yên
4,36042000,PGD Chợ Đậu,106.343223,20.433061,36044000,PGD Vũ Thư,106.288684,20.435725,7.3,5.690572,Hưng Yên

In [47]:
df_final = pd.concat([df_thay_doi_new_etl, ml_khong_doi], ignore_index=True)

In [48]:
df_final.to_excel(r'/home/trungdt2/Documents/GIS_VTB_Project2025/crawl_all_khoang_cach/data_20260313/full_trong_tinh_sau_sat_nhap_20260312.xlsx', index = False)

In [49]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63506 entries, 0 to 63505
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ma_phong_ban_1           63506 non-null  object
 1   ten_phong_ban_1          63506 non-null  object
 2   kinh_do_1                63506 non-null  object
 3   vi_do_1                  63506 non-null  object
 4   ma_phong_ban_2           63506 non-null  object
 5   ten_phong_ban_2          63506 non-null  object
 6   kinh_do_2                63506 non-null  object
 7   vi_do_2                  63506 non-null  object
 8   khoang_cach_duong_bo_km  63228 non-null  float64
 9   khoang_cach_chim_bay_km  63506 non-null  float64
 10  tinh_thanh_sau_sap_nhap  63506 non-null  object
dtypes: float64(2), object(9)
memory usage: 5.3+ MB

# xu ly so luong diem gan nhat

In [50]:
df_final.columns

Index(['ma_phong_ban_1', 'ten_phong_ban_1', 'kinh_do_1', 'vi_do_1',
       'ma_phong_ban_2', 'ten_phong_ban_2', 'kinh_do_2', 'vi_do_2',
       'khoang_cach_duong_bo_km', 'khoang_cach_chim_bay_km',
       'tinh_thanh_sau_sap_nhap'],
      dtype='object')

In [51]:
df_final.head()

,ma_phong_ban_1,ten_phong_ban_1,kinh_do_1,vi_do_1,ma_phong_ban_2,ten_phong_ban_2,kinh_do_2,vi_do_2,khoang_cach_duong_bo_km,khoang_cach_chim_bay_km,tinh_thanh_sau_sap_nhap
0,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94030000,PGD Lý Thường Kiệt,106.65765,10.771648,3.7,2.662460,TP. Hồ Chí Minh
1,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94031000,PGD Ngô Gia Tự,106.674839,10.767055,2.0,0.832554,TP. Hồ Chí Minh
2,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94032000,PGD Ngô Quyền,106.664916,10.762539,2.4,2.026162,TP. Hồ Chí Minh
3,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94033000,PGD Tô Hiến Thành,106.668015,10.779648,3.6,1.877803,TP. Hồ Chí Minh
4,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94200000,CN 11 Thành phố Hồ Chí Minh,106.647436,10.756821,5.5,4.035046,TP. Hồ Chí Minh

In [52]:
df_final['ma_don_vi_1'] = df_final['ma_phong_ban_1']//100000
df_final['ma_don_vi_2'] = df_final['ma_phong_ban_2']//100000

In [53]:
df = df_final.copy()

# ------------------------------
# điều kiện cùng đơn vị
# ------------------------------
df['cung_don_vi'] = df['ma_don_vi_1'] == df['ma_don_vi_2']

# ------------------------------
# SL_diem_0.5km
# ------------------------------
sl_05 = (
    df[df['khoang_cach_duong_bo_km'] <= 0.5]
    .groupby('ma_phong_ban_1')
    .size()
    .rename('SL_diem_0.5km')
)

# ------------------------------
# SL_diem_1km
# ------------------------------
sl_1 = (
    df[df['khoang_cach_duong_bo_km'] <= 1]
    .groupby('ma_phong_ban_1')
    .size()
    .rename('SL_diem_1km')
)

# ------------------------------
# SL_diem_0.5km_cung_donvi
# ------------------------------
sl_05_dv = (
    df[(df['khoang_cach_duong_bo_km'] <= 0.5) & (df['cung_don_vi'])]
    .groupby('ma_phong_ban_1')
    .size()
    .rename('SL_diem_0.5km_cung_donvi')
)

# ------------------------------
# SL_diem_1km_cung_donvi
# ------------------------------
sl_1_dv = (
    df[(df['khoang_cach_duong_bo_km'] <= 1) & (df['cung_don_vi'])]
    .groupby('ma_phong_ban_1')
    .size()
    .rename('SL_diem_1km_cung_donvi')
)

# ------------------------------
# merge vào bảng gốc
# ------------------------------
df_ket_qua = (
    df[['ma_phong_ban_1','ten_phong_ban_1','kinh_do_1','vi_do_1','tinh_thanh_sau_sap_nhap']]
    .drop_duplicates()
    .merge(sl_05, on='ma_phong_ban_1', how='left')
    .merge(sl_1, on='ma_phong_ban_1', how='left')
    .merge(sl_05_dv, on='ma_phong_ban_1', how='left')
    .merge(sl_1_dv, on='ma_phong_ban_1', how='left')
)

df_ket_qua = df_ket_qua.fillna(0)

/tmp/ipykernel_20925/2159042404.py:60: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_ket_qua = df_ket_qua.fillna(0)

In [54]:
df_ket_qua.head(20)

,ma_phong_ban_1,ten_phong_ban_1,kinh_do_1,vi_do_1,tinh_thanh_sau_sap_nhap,SL_diem_0.5km,SL_diem_1km,SL_diem_0.5km_cung_donvi,SL_diem_1km_cung_donvi
0,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,TP. Hồ Chí Minh,0.0,0.0,0.0,0.0
1,90630000,PGD Ba Tháng Hai,106.668990,10.768816,TP. Hồ Chí Minh,0.0,2.0,0.0,0.0
2,90632000,PGD Vườn Chuối,106.683993,10.772327,TP. Hồ Chí Minh,0.0,0.0,0.0,0.0
3,90635000,PGD Đô Thành,106.675662,10.789236,TP. Hồ Chí Minh,0.0,0.0,0.0,0.0
4,90636000,PGD Hai Bà Trưng,106.690422,10.789392,TP. Hồ Chí Minh,0.0,1.0,0.0,0.0
5,90800000,CN 4 Thành phố Hồ Chí Minh,106.702562,10.765946,TP. Hồ Chí Minh,0.0,0.0,0.0,0.0
6,12638000,PGD Giảng Võ,105.816620,21.019465,TP. Hà Nội,1.0,1.0,0.0,0.0
7,12640000,PGD Hồ Giám,105.834118,21.027856,TP. Hà Nội,1.0,2.0,1.0,1.0
8,90834000,PGD Văn Thánh,106.714262,10.801798,TP. Hồ Chí Minh,0.0,1.0,0.0,0.0
9,90835000,PGD Phan Văn Trị,106.691874,10.824222,TP. Hồ Chí Minh,0.0,1.0,0.0,0.0
10,90836000,PGD Nguyễn Lương Bằng,106.728449,10.717443,TP. Hồ Chí Minh,0.0,0.0,0.0,0.0
11,91000000,CN Nam Sài Gòn,106.700239,10.739119,TP. Hồ Chí Minh,0.0,0.0,0.0,0.0
12,91030000,PGD Phú Mỹ Hưng,106.705535,10.729180,TP. Hồ Chí Minh,0.0,0.0,0.0,0.0
13,91031000,PGD Trần Xuân Soạn,106.705535,10.751713,TP. Hồ Chí Minh,0.0,0.0,0.0,0.0
14,91032000,PGD Hùynh Tấn Phát,106.736826,10.714542,TP. Hồ Chí Minh,0.0,0.0,0.0,0.0
15,91033000,PGD Nguyễn Văn Cừ,106.692575,10.760921,TP. Hồ Chí Minh,0.0,1.0,0.0,0.0
16,13140000,PGD Phú Thịnh,105.964789,21.019273,TP. Hà Nội,0.0,0.0,0.0,0.0
17,13600000,CN Hoàng Mai,105.850084,20.983274,TP. Hà Nội,0.0,0.0,0.0,0.0
18,13630000,PGD Minh Khai,105.862893,20.995312,TP. Hà Nội,0.0,1.0,0.0,0.0
19,13632000,PGD Nam Hà Nội,105.848030,20.931189,TP. Hà Nội,0.0,0.0,0.0,0.0

In [55]:
df = df_final.copy()

# bỏ self-pair nếu có
df = df[df['ma_phong_ban_1'] != df['ma_phong_ban_2']].copy()

# cờ cùng đơn vị
df['cung_don_vi'] = df['ma_don_vi_1'] == df['ma_don_vi_2']

# hàm gộp tên, bỏ trùng, nối bằng ;
def gop_ten(series):
    vals = (
        series.dropna()
        .astype(str)
        .str.strip()
    )
    vals = vals[vals != '']
    vals = pd.unique(vals)
    return '; '.join(vals)

# 1) Phongban_0.5km
pb_05 = (
    df[df['khoang_cach_duong_bo_km'] <= 0.5]
    .groupby('ma_phong_ban_1')['ten_phong_ban_2']
    .apply(gop_ten)
    .rename('Phongban_0.5km')
)

# 2) Phongban_1km
pb_1 = (
    df[df['khoang_cach_duong_bo_km'] <= 1]
    .groupby('ma_phong_ban_1')['ten_phong_ban_2']
    .apply(gop_ten)
    .rename('Phongban_1km')
)

# 3) phongban_1km (cột mới)
pb_1_lower = (
    df[df['khoang_cach_duong_bo_km'] <= 1]
    .groupby('ma_phong_ban_1')['ten_phong_ban_2']
    .apply(gop_ten)
    .rename('phongban_1km')
)

# 4) Phongban_0.5km_cung_donvi
pb_05_dv = (
    df[(df['khoang_cach_duong_bo_km'] <= 0.5) & (df['cung_don_vi'])]
    .groupby('ma_phong_ban_1')['ten_phong_ban_2']
    .apply(gop_ten)
    .rename('Phongban_0.5km_cung_donvi')
)

# 5) Phongban_1km_cung_donvi
pb_1_dv = (
    df[(df['khoang_cach_duong_bo_km'] <= 1) & (df['cung_don_vi'])]
    .groupby('ma_phong_ban_1')['ten_phong_ban_2']
    .apply(gop_ten)
    .rename('Phongban_1km_cung_donvi')
)

# merge vào bảng kết quả
df_ket_qua = (
    df_ket_qua
    .merge(pb_05, on='ma_phong_ban_1', how='left')
    .merge(pb_1, on='ma_phong_ban_1', how='left')
    .merge(pb_1_lower, on='ma_phong_ban_1', how='left')   # cột mới
    .merge(pb_05_dv, on='ma_phong_ban_1', how='left')
    .merge(pb_1_dv, on='ma_phong_ban_1', how='left')
)

# fill rỗng
cols_text = [
    'Phongban_0.5km',
    'Phongban_1km',
    'phongban_1km',
    'Phongban_0.5km_cung_donvi',
    'Phongban_1km_cung_donvi'
]

df_ket_qua[cols_text] = df_ket_qua[cols_text].fillna('')

In [56]:
df_ket_qua.head()

,ma_phong_ban_1,ten_phong_ban_1,kinh_do_1,vi_do_1,tinh_thanh_sau_sap_nhap,SL_diem_0.5km,SL_diem_1km,SL_diem_0.5km_cung_donvi,SL_diem_1km_cung_donvi,Phongban_0.5km,Phongban_1km,phongban_1km,Phongban_0.5km_cung_donvi,Phongban_1km_cung_donvi
0,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,TP. Hồ Chí Minh,0.0,0.0,0.0,0.0,,,,,
1,90630000,PGD Ba Tháng Hai,106.668990,10.768816,TP. Hồ Chí Minh,0.0,2.0,0.0,0.0,,PGD LaKai; PGD Ngô Quyền,PGD LaKai; PGD Ngô Quyền,,
2,90632000,PGD Vườn Chuối,106.683993,10.772327,TP. Hồ Chí Minh,0.0,0.0,0.0,0.0,,,,,
3,90635000,PGD Đô Thành,106.675662,10.789236,TP. Hồ Chí Minh,0.0,0.0,0.0,0.0,,,,,
4,90636000,PGD Hai Bà Trưng,106.690422,10.789392,TP. Hồ Chí Minh,0.0,1.0,0.0,0.0,,PGD Đinh Tiên Hoàng,PGD Đinh Tiên Hoàng,,

In [57]:
df_ket_qua.to_excel(r'/home/trungdt2/Documents/GIS_VTB_Project2025/crawl_all_khoang_cach/data_20260313/template_sheet1.xlsx',index=False)

In [58]:
danh_sach_tinh_cu_moi = pd.read_excel(r'/home/trungdt2/Documents/GIS_VTB_Project2025/crawl_all_khoang_cach/data_20260313/danh_sach_tinh_cu_moi.xlsx')

In [59]:
danh_sach_tinh_cu_moi.head()

   ma_don_vi Tinh_thanh(cu) Tinh_thanh(moi)
0        106     TP. Hà Nội      TP. Hà Nội
1        122     TP. Hà Nội      TP. Hà Nội
2        124     TP. Hà Nội      TP. Hà Nội
3        126     TP. Hà Nội      TP. Hà Nội
4        127     TP. Hà Nội      TP. Hà Nội

In [60]:
df_final.head()

,ma_phong_ban_1,ten_phong_ban_1,kinh_do_1,vi_do_1,ma_phong_ban_2,ten_phong_ban_2,kinh_do_2,vi_do_2,khoang_cach_duong_bo_km,khoang_cach_chim_bay_km,tinh_thanh_sau_sap_nhap,ma_don_vi_1,ma_don_vi_2
0,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94030000,PGD Lý Thường Kiệt,106.65765,10.771648,3.7,2.662460,TP. Hồ Chí Minh,906,940
1,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94031000,PGD Ngô Gia Tự,106.674839,10.767055,2.0,0.832554,TP. Hồ Chí Minh,906,940
2,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94032000,PGD Ngô Quyền,106.664916,10.762539,2.4,2.026162,TP. Hồ Chí Minh,906,940
3,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94033000,PGD Tô Hiến Thành,106.668015,10.779648,3.6,1.877803,TP. Hồ Chí Minh,906,940
4,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94200000,CN 11 Thành phố Hồ Chí Minh,106.647436,10.756821,5.5,4.035046,TP. Hồ Chí Minh,906,942

In [61]:
df_final_2 = pd.merge(df_final,danh_sach_tinh_cu_moi, left_on='ma_don_vi_1', right_on='ma_don_vi', how='left')

In [62]:
df_final_2.head()

,ma_phong_ban_1,ten_phong_ban_1,kinh_do_1,vi_do_1,ma_phong_ban_2,ten_phong_ban_2,kinh_do_2,vi_do_2,khoang_cach_duong_bo_km,khoang_cach_chim_bay_km,tinh_thanh_sau_sap_nhap,ma_don_vi_1,ma_don_vi_2,ma_don_vi,Tinh_thanh(cu),Tinh_thanh(moi)
0,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94030000,PGD Lý Thường Kiệt,106.65765,10.771648,3.7,2.662460,TP. Hồ Chí Minh,906,940,906,TP. Hồ Chí Minh,TP. Hồ Chí Minh
1,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94031000,PGD Ngô Gia Tự,106.674839,10.767055,2.0,0.832554,TP. Hồ Chí Minh,906,940,906,TP. Hồ Chí Minh,TP. Hồ Chí Minh
2,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94032000,PGD Ngô Quyền,106.664916,10.762539,2.4,2.026162,TP. Hồ Chí Minh,906,940,906,TP. Hồ Chí Minh,TP. Hồ Chí Minh
3,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94033000,PGD Tô Hiến Thành,106.668015,10.779648,3.6,1.877803,TP. Hồ Chí Minh,906,940,906,TP. Hồ Chí Minh,TP. Hồ Chí Minh
4,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,94200000,CN 11 Thành phố Hồ Chí Minh,106.647436,10.756821,5.5,4.035046,TP. Hồ Chí Minh,906,942,906,TP. Hồ Chí Minh,TP. Hồ Chí Minh

In [63]:
df_final_2 = df_final_2.drop(columns=['tinh_thanh_sau_sap_nhap','ma_don_vi'], axis=1)

In [64]:
df_final_2.columns

Index(['ma_phong_ban_1', 'ten_phong_ban_1', 'kinh_do_1', 'vi_do_1',
       'ma_phong_ban_2', 'ten_phong_ban_2', 'kinh_do_2', 'vi_do_2',
       'khoang_cach_duong_bo_km', 'khoang_cach_chim_bay_km', 'ma_don_vi_1',
       'ma_don_vi_2', 'Tinh_thanh(cu)', 'Tinh_thanh(moi)'],
      dtype='object')

In [65]:
import pandas as pd
import numpy as np

df = df_final_2.copy()

# =========================================
# 1. Chuẩn hóa dữ liệu
# =========================================
num_cols = [
    'kinh_do_1', 'vi_do_1',
    'kinh_do_2', 'vi_do_2',
    'khoang_cach_duong_bo_km',
    'khoang_cach_chim_bay_km'
]

for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

text_cols = [
    'ma_phong_ban_1', 'ten_phong_ban_1',
    'ma_phong_ban_2', 'ten_phong_ban_2',
    'ma_don_vi_1', 'ma_don_vi_2',
    'Tinh_thanh(cu)', 'Tinh_thanh(moi)'
]

for col in text_cols:
    df[col] = df[col].astype(str).str.strip()

# bỏ self-pair: A -> A
df = df[df['ma_phong_ban_1'] != df['ma_phong_ban_2']].copy()

# =========================================
# 2. Base table: 1 dòng / điểm giao dịch gốc
# =========================================
base = (
    df[
        [
            'ma_phong_ban_1', 'ten_phong_ban_1',
            'kinh_do_1', 'vi_do_1',
            'ma_don_vi_1',
            'Tinh_thanh(cu)', 'Tinh_thanh(moi)'
        ]
    ]
    .drop_duplicates(subset=['ma_phong_ban_1'])
    .copy()
)

# =========================================
# 3. Hàm lấy điểm gần nhất
# =========================================
def lay_diem_gan_nhat(df_in, distance_col, prefix):
    """
    df_in: dataframe đã lọc đúng phạm vi cần xét
    distance_col: cột khoảng cách để tìm min
    prefix: tiền tố tên cột output
    """
    tmp = df_in.dropna(subset=[distance_col]).copy()
    tmp = tmp.sort_values(['ma_phong_ban_1', distance_col, 'ma_phong_ban_2'])

    nearest = (
        tmp.groupby('ma_phong_ban_1', as_index=False)
           .first()[['ma_phong_ban_1', 'ma_phong_ban_2', 'ten_phong_ban_2', distance_col]]
           .rename(columns={
               'ma_phong_ban_2': f'{prefix}_ma_pgd',
               'ten_phong_ban_2': f'{prefix}_ten_pgd',
               distance_col: f'{prefix}_khoang_cach'
           })
    )
    return nearest

# =========================================
# 4. Gần nhất trong tỉnh cũ - đường chim bay
# =========================================
# Vì mỗi dòng đang là cặp trong cùng tỉnh cũ/tỉnh mới tương ứng của điểm 1,
# nếu dữ liệu của bạn đã được tạo theo logic cùng tỉnh thì có thể dùng trực tiếp.
# Nếu muốn chặt chẽ hơn thì chỉ cần giữ nguyên từng tỉnh cũ của điểm 1.
df_tinh_cu_cb = df.copy()

nearest_tinh_cu_cb = lay_diem_gan_nhat(
    df_in=df_tinh_cu_cb,
    distance_col='khoang_cach_chim_bay_km',
    prefix='tinh_cu_chim_bay'
)

# =========================================
# 5. Gần nhất trong tỉnh cũ - đường thực tế
# =========================================
df_tinh_cu_db = df.copy()

nearest_tinh_cu_db = lay_diem_gan_nhat(
    df_in=df_tinh_cu_db,
    distance_col='khoang_cach_duong_bo_km',
    prefix='tinh_cu_duong_bo'
)

# =========================================
# 6. Gần nhất trong CN - đường chim bay
# =========================================
df_cn_cb = df[df['ma_don_vi_1'] == df['ma_don_vi_2']].copy()

nearest_cn_cb = lay_diem_gan_nhat(
    df_in=df_cn_cb,
    distance_col='khoang_cach_chim_bay_km',
    prefix='cn_chim_bay'
)

# =========================================
# 7. Gần nhất trong CN - đường thực tế
# =========================================
df_cn_db = df[df['ma_don_vi_1'] == df['ma_don_vi_2']].copy()

nearest_cn_db = lay_diem_gan_nhat(
    df_in=df_cn_db,
    distance_col='khoang_cach_duong_bo_km',
    prefix='cn_duong_bo'
)

# =========================================
# 8. Gần nhất trong tỉnh mới - đường thực tế
# =========================================
# Nếu toàn bộ cặp đã cùng Tinh_thanh(moi) thì dùng trực tiếp.
# Nếu không, cần có thêm cột tỉnh mới của điểm 2 để lọc chặt chẽ hơn.
df_tinh_moi_db = df.copy()

nearest_tinh_moi_db = lay_diem_gan_nhat(
    df_in=df_tinh_moi_db,
    distance_col='khoang_cach_duong_bo_km',
    prefix='tinh_moi_duong_bo'
)

# =========================================
# 9. Merge toàn bộ vào base
# =========================================
result = (
    base
    .merge(nearest_tinh_cu_cb, on='ma_phong_ban_1', how='left')
    .merge(nearest_tinh_cu_db, on='ma_phong_ban_1', how='left')
    .merge(nearest_cn_cb, on='ma_phong_ban_1', how='left')
    .merge(nearest_cn_db, on='ma_phong_ban_1', how='left')
    .merge(nearest_tinh_moi_db, on='ma_phong_ban_1', how='left')
)

# =========================================
# 10. Rename cho giống logic trong file Excel
# =========================================
result = result.rename(columns={
    'ma_phong_ban_1': 'Mã PGD gốc',
    'ten_phong_ban_1': 'Tên PGD gốc',
    'kinh_do_1': 'Kinh độ',
    'vi_do_1': 'Vĩ độ',
    'ma_don_vi_1': 'Mã đơn vị',
    'Tinh_thanh(cu)': 'Tỉnh thành cũ',
    'Tinh_thanh(moi)': 'Tỉnh thành mới',

    'tinh_cu_chim_bay_ma_pgd': 'Mã PGD_gan_nhat_tinh_cu_chim_bay',
    'tinh_cu_chim_bay_ten_pgd': 'Tên PGD_gan_nhat_tinh_cu_chim_bay',
    'tinh_cu_chim_bay_khoang_cach': 'Khoảng cách_tinh_cu_chim_bay',

    'tinh_cu_duong_bo_ma_pgd': 'Mã PGD_gan_nhat_tinh_cu_duong_bo',
    'tinh_cu_duong_bo_ten_pgd': 'Tên PGD_gan_nhat_tinh_cu_duong_bo',
    'tinh_cu_duong_bo_khoang_cach': 'Khoảng cách_tinh_cu_duong_bo',

    'cn_chim_bay_ma_pgd': 'Mã PGD_gan_nhat_CN_chim_bay',
    'cn_chim_bay_ten_pgd': 'Tên PGD_gan_nhat_CN_chim_bay',
    'cn_chim_bay_khoang_cach': 'Khoảng cách_CN_chim_bay',

    'cn_duong_bo_ma_pgd': 'Mã PGD_gan_nhat_CN_duong_bo',
    'cn_duong_bo_ten_pgd': 'Tên PGD_gan_nhat_CN_duong_bo',
    'cn_duong_bo_khoang_cach': 'Khoảng cách_CN_duong_bo',

    'tinh_moi_duong_bo_ma_pgd': 'Mã PGD_gan_nhat_tinh_moi_duong_bo',
    'tinh_moi_duong_bo_ten_pgd': 'Tên PGD_gan_nhat_tinh_moi_duong_bo',
    'tinh_moi_duong_bo_khoang_cach': 'Khoảng cách_tinh_moi_duong_bo',
})

In [66]:
result.head()

,Mã PGD gốc,Tên PGD gốc,Kinh độ,Vĩ độ,Mã đơn vị,Tỉnh thành cũ,Tỉnh thành mới,Mã PGD_gan_nhat_tinh_cu_chim_bay,Tên PGD_gan_nhat_tinh_cu_chim_bay,Khoảng cách_tinh_cu_chim_bay,...,Khoảng cách_tinh_cu_duong_bo,Mã PGD_gan_nhat_CN_chim_bay,Tên PGD_gan_nhat_CN_chim_bay,Khoảng cách_CN_chim_bay,Mã PGD_gan_nhat_CN_duong_bo,Tên PGD_gan_nhat_CN_duong_bo,Khoảng cách_CN_duong_bo,Mã PGD_gan_nhat_tinh_moi_duong_bo,Tên PGD_gan_nhat_tinh_moi_duong_bo,Khoảng cách_tinh_moi_duong_bo
0,90600000,CN 3 Thành phố Hồ Chí Minh,106.681948,10.769755,906,TP. Hồ Chí Minh,TP. Hồ Chí Minh,90632000,PGD Vườn Chuối,0.362840,...,1.40,90632000,PGD Vườn Chuối,0.362840,90632000,PGD Vườn Chuối,1.5,94000000,CN 10 Thành phố Hồ Chí Minh,1.40
1,90630000,PGD Ba Tháng Hai,106.668990,10.768816,906,TP. Hồ Chí Minh,TP. Hồ Chí Minh,94000000,CN 10 Thành phố Hồ Chí Minh,0.589387,...,1.00,90600000,CN 3 Thành phố Hồ Chí Minh,1.419295,90600000,CN 3 Thành phố Hồ Chí Minh,1.8,92636000,PGD LaKai,1.00
2,90632000,PGD Vườn Chuối,106.683993,10.772327,906,TP. Hồ Chí Minh,TP. Hồ Chí Minh,90600000,CN 3 Thành phố Hồ Chí Minh,0.362840,...,1.50,90600000,CN 3 Thành phố Hồ Chí Minh,0.362840,90600000,CN 3 Thành phố Hồ Chí Minh,1.5,90600000,CN 3 Thành phố Hồ Chí Minh,1.50
3,90635000,PGD Đô Thành,106.675662,10.789236,906,TP. Hồ Chí Minh,TP. Hồ Chí Minh,93000000,CN Gia Định,0.838229,...,1.50,90636000,PGD Hai Bà Trưng,1.612327,90636000,PGD Hai Bà Trưng,2.4,94534000,PGD Lê Văn Sỹ,1.50
4,90636000,PGD Hai Bà Trưng,106.690422,10.789392,906,TP. Hồ Chí Minh,TP. Hồ Chí Minh,90043000,PGD Đinh Tiên Hoàng,0.644216,...,0.85,90635000,PGD Đô Thành,1.612327,90635000,PGD Đô Thành,2.4,90043000,PGD Đinh Tiên Hoàng,0.85

In [67]:
result.to_excel(r'/home/trungdt2/Documents/GIS_VTB_Project2025/crawl_all_khoang_cach/data_20260313/template_sheet2.xlsx',index=False)